In [ ]:
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.8.6
aiosignal                        1.3.1
alabaster                        0.7.13
albumentations                   1.3.1
altair                           4.2.2
anyio                            3.7.1
appdirs                          1.4.4
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array-record                     0.5.0
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.0
attrs                            23.1.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.13.1
backcall                         0.2.0
beautifulsoup4                   4.11.2
bidict                           0.22.1
b

In [ ]:
from keras import Sequential

In [ ]:
from keras.layers import Dense, SimpleRNN

In [ ]:
model  = Sequential()

In [ ]:
model.add(SimpleRNN(3,input_shape=(4,5)))
model.add(Dense(1, activation= 'sigmoid'))  # by defout it takes tanh activation function

In [ ]:
model.summary()  # for getting no. of tranable parameter. here it is 31. If we will add more layer then we can call it deep RNN

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 3)                 27        
                                                                 
 dense (Dense)               (None, 1)                 4         
                                                                 
Total params: 31 (124.00 Byte)
Trainable params: 31 (124.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.get_weights()   # to check the wigths taken by neuron nodes

[array([[ 0.7024514 ,  0.6481654 ,  0.1905654 ],
        [ 0.75769395, -0.18743777, -0.36797154],
        [ 0.5211503 ,  0.07343709, -0.41911724],
        [ 0.7741795 ,  0.4534921 , -0.7704507 ],
        [-0.63426995,  0.6307351 ,  0.46911055]], dtype=float32),
 array([[ 0.4944346 , -0.48081863, -0.72411865],
        [ 0.746394  ,  0.6617902 ,  0.0702121 ],
        [ 0.4454554 , -0.57519305,  0.68609214]], dtype=float32),
 array([0., 0., 0.], dtype=float32),
 array([[-0.00341642],
        [ 0.18040645],
        [ 0.6521131 ]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
model.get_weights()[0]   # the weights from input layer to hindden layer and its shape

array([[ 0.7024514 ,  0.6481654 ,  0.1905654 ],
       [ 0.75769395, -0.18743777, -0.36797154],
       [ 0.5211503 ,  0.07343709, -0.41911724],
       [ 0.7741795 ,  0.4534921 , -0.7704507 ],
       [-0.63426995,  0.6307351 ,  0.46911055]], dtype=float32)

In [ ]:
model.get_weights()[0].shape

(5, 3)

In [ ]:
model.get_weights()[1]  # the weights of feedbak loop of RNN which it is giving to each nodes of hidden layer by each node and its shape

array([[ 0.4944346 , -0.48081863, -0.72411865],
       [ 0.746394  ,  0.6617902 ,  0.0702121 ],
       [ 0.4454554 , -0.57519305,  0.68609214]], dtype=float32)

In [ ]:
model.get_weights()[1].shape

(3, 3)

In [ ]:
model.get_weights()[3]  # the weights from hidden layer to output layer

array([[-0.00341642],
       [ 0.18040645],
       [ 0.6521131 ]], dtype=float32)

In [ ]:
model.get_weights()[3].shape

(3, 1)

In [ ]:
model.get_weights()[2]   # it is bias weight

array([0., 0., 0.], dtype=float32)

# Lets check from IMDB dataset with RNN

In [ ]:
from keras.datasets import imdb

In [ ]:
#imdb.load_data()   -- Data downloading from dataset imdb
(X_train,y_train),(X_test,y_test)=imdb.load_data()

17464789/17464789 [==============================] - 0s 0us/step


In [ ]:
len(X_train[0])   #finding length, sentance wise

218

In [ ]:
len(X_train[0])

218

In [ ]:
len(X_train[2])

141

In [ ]:
# As length is not fixed hence finding minimum length of sentence from the dataset

mylist=[]
for review in X_train:
  mylist.append(len(review))
min(mylist)

11

In [11]:
X_train   #  These all are encoded no. os the sentences. We have checked below what is the encoded sentence

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [12]:
X_train.shape

(25000,)

In [13]:
X_test.shape

(25000,)

In [14]:
# Lets check how sentence encode happens

import numpy as np
sent=[

      "india won worldcup",
      "rohit played very well",
      "above all is my imagination",
      "bharat mata ki jay",
      "definatly we goona win next worldcup"
]

In [15]:
sent

['india won worldcup',
 'rohit played very well',
 'above all is my imagination',
 'bharat mata ki jay',
 'definatly we goona win next worldcup']

In [16]:
# it is performing integer encoding
from keras.preprocessing.text import Tokenizer

In [18]:
tokenizer=Tokenizer()

In [19]:
tokenizer.fit_on_texts(sent)

In [21]:
#tokenizer.index_word  # it will give index then words

tokenizer.word_index   # both working good

{'worldcup': 1,
 'india': 2,
 'won': 3,
 'rohit': 4,
 'played': 5,
 'very': 6,
 'well': 7,
 'above': 8,
 'all': 9,
 'is': 10,
 'my': 11,
 'imagination': 12,
 'bharat': 13,
 'mata': 14,
 'ki': 15,
 'jay': 16,
 'definatly': 17,
 'we': 18,
 'goona': 19,
 'win': 20,
 'next': 21}

In [22]:
tokenizer.word_counts

OrderedDict([('india', 1),
             ('won', 1),
             ('worldcup', 2),
             ('rohit', 1),
             ('played', 1),
             ('very', 1),
             ('well', 1),
             ('above', 1),
             ('all', 1),
             ('is', 1),
             ('my', 1),
             ('imagination', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 1),
             ('jay', 1),
             ('definatly', 1),
             ('we', 1),
             ('goona', 1),
             ('win', 1),
             ('next', 1)])

In [23]:
tokenizer.document_count

5

In [24]:
encoding=tokenizer.texts_to_sequences(sent)   # Endcoding each words of sentence

In [25]:
encoding

[[2, 3, 1],
 [4, 5, 6, 7],
 [8, 9, 10, 11, 12],
 [13, 14, 15, 16],
 [17, 18, 19, 20, 21, 1]]

In [26]:
from keras.utils import pad_sequences

In [30]:
#pad_sequences(encoding ,padding='pre')  # for placing zero in the begining

pad_sequences(encoding ,padding='post')  # for placing zero in the ending

array([[ 2,  3,  1,  0,  0,  0],
       [ 4,  5,  6,  7,  0,  0],
       [ 8,  9, 10, 11, 12,  0],
       [13, 14, 15, 16,  0,  0],
       [17, 18, 19, 20, 21,  1]], dtype=int32)

In [49]:
pad_sequences(encoding ,padding='pre')    # for placing zero in the begining

array([[ 0,  0,  0,  2,  3,  1],
       [ 0,  0,  4,  5,  6,  7],
       [ 0,  8,  9, 10, 11, 12],
       [ 0,  0, 13, 14, 15, 16],
       [17, 18, 19, 20, 21,  1]], dtype=int32)

In [31]:
X_train

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [33]:
y_train

array([1, 0, 0, ..., 0, 1, 0])

In [75]:
X_train=pad_sequences(X_train ,padding="post",maxlen=60)  # taking average 50 length of  sentences. But we can take also, then it will take more time
# for training

In [76]:
X_test=pad_sequences(X_test ,padding="post",maxlen=60)

In [78]:
from keras import Sequential

model=Sequential()

In [79]:
from keras.layers import Dense, SimpleRNN

model.add(SimpleRNN(32,input_shape=(60,1)))

In [80]:
model.add(Dense(1,activation="sigmoid"))

In [81]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_5 (SimpleRNN)    (None, 32)                1088      
                                                                 
 dense_4 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1121 (4.38 KB)
Trainable params: 1121 (4.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [82]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [83]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=5)  # MODEL TRAINING

Epoch 1/5
782/782 [==============================] - 35s 43ms/step - loss: 0.6937 - accuracy: 0.5025 - val_loss: 0.6934 - val_accuracy: 0.5000
Epoch 2/5
782/782 [==============================] - 34s 43ms/step - loss: 0.6933 - accuracy: 0.5021 - val_loss: 0.6932 - val_accuracy: 0.5000
Epoch 3/5
782/782 [==============================] - 33s 42ms/step - loss: 0.6933 - accuracy: 0.5022 - val_loss: 0.6932 - val_accuracy: 0.5009
Epoch 4/5
782/782 [==============================] - 34s 44ms/step - loss: 0.6933 - accuracy: 0.5010 - val_loss: 0.6932 - val_accuracy: 0.5000
Epoch 5/5
782/782 [==============================] - 33s 43ms/step - loss: 0.6932 - accuracy: 0.5048 - val_loss: 0.6931 - val_accuracy: 0.5000


In [84]:
model.predict(X_test)   # Almost 50% accuracy in 50 word count limit

782/782 [==============================] - 6s 7ms/step


array([[0.49851176],
       [0.49851176],
       [0.49851176],
       ...,
       [0.49851176],
       [0.49851176],
       [0.49851176]], dtype=float32)

In [85]:
loss,accuracy=model.evaluate(X_test,y_test)

782/782 [==============================] - 6s 8ms/step - loss: 0.6931 - accuracy: 0.5000


In [86]:
loss

0.693145751953125

In [87]:
accuracy

0.5